management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: "true"
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: "true"
  datasource:
    testWhileIdle: "true"
    validationQuery: SELECT 1
    platform: postgres
  cloud:
    loadbalancer:
      ribbon:
        enabled: "false"
  database:
    driverClassName: org.postgresql.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
server:
  port: "8081"
