server:
  port: "8081"
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: "true"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: "true"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: organization-service-pool
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 10

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://{KEYCLOAK_HOST:localhost}:8180/realms/master

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8070/eureka/

resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5 # Altertavie of ringBufferSizeInClosedState
        permittedNumberOfCallsInHalfOpenState: 3 # Altertavie of ringBufferSizeInHalfOpenState
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException

      organizationService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 20000ms
        failureRateThreshold: 60
